AllCops:
  Exclude:
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'files/default/vendor/**/*'

NumericLiterals:
  Enabled: false

SingleSpaceBeforeFirstArg:
  Enabled: false

Metrics/LineLength:
  Max: 100
